version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      couchbase:
        condition: service_healthy
    environment:
      - SPRING_COUCHBASE_CONNECTION-STRING=couchbase://couchbase
      - SPRING_COUCHBASE_USERNAME=Administrator
      - SPRING_COUCHBASE_PASSWORD=password
      - SPRING_COUCHBASE_BUCKET-NAME=todo
    networks:
      - app-network
    command: ["/wait-for-couchbase.sh", "couchbase", "java", "-jar", "app.jar"]

  couchbase:
    image: couchbase:enterprise-6.6.0
    platform: linux/amd64
    ports:
      - "28091-28096:8091-8096"
      - "21210-21211:11210-11211"
    volumes:
      - couchbase_data:/opt/couchbase/var
      - ./couchbase/init-couchbase.sh:/opt/couchbase/init-couchbase.sh
    environment:
      - COUCHBASE_ADMINISTRATOR_USERNAME=Administrator
      - COUCHBASE_ADMINISTRATOR_PASSWORD=password
    command: sh -c "/entrypoint.sh couchbase-server & sleep 15 && /opt/couchbase/init-couchbase.sh"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "test", "-f", "/opt/couchbase/var/lib/couchbase/init_complete"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s

networks:
  app-network:
    driver: bridge

volumes:
  couchbase_data:
