app:
  jwtSecret: 123123
  jwtExpirationInMs: 6000000

spring:
  couchbase:
    connection-string: ${SPRING_COUCHBASE_CONNECTION-STRING:couchbase://couchbase}
    username: ${SPRING_COUCHBASE_USERNAME:Administrator}
    password: ${SPRING_COUCHBASE_PASSWORD:password}
    bucket-name: ${SPRING_COUCHBASE_BUCKET-NAME:todo}
    env:
      io:
        enableDnsSrv: false

  data:
    couchbase:
      auto-index: true

logging:
  level:
    com.erdi.todoapp: DEBUG
    org.springframework.data.couchbase: DEBUG
    com.couchbase.client: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
