app:
  jwtSecret: 123123
  jwtExpirationInMs: 6000000

spring:
  couchbase:
    connection-string: couchbase://couchbase
    username: Administrator
    password: password
  data:
    couchbase:
      bucket-name: todo
      auto-index: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
