app:
  jwtSecret: 123123
  jwtExpirationInMs: 6000000

spring:
  couchbase:
    connection-string: couchbase://localhost
    username: Administrator
    password: password
    bucket-name: todo

  data:
    couchbase:
      auto-index: true

logging:
  level:
    com.erdi.todoapp: DEBUG
    org.springframework.data.couchbase: DEBUG
    com.couchbase.client: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
