app:
  jwtSecret: 123123
  jwtExpirationInMs: 6000000

spring:
  couchbase:
    connection: couchbase://localhost
    username: Administrator
    password: password
    bucket: todo
    env:
      io:
        enableDnsSrv: false

  data:
    couchbase:
      auto-index: true

logging:
  level:
    com.erdi.todoapp: DEBUG
    org.springframework.data.couchbase: DEBUG
    com.couchbase.client: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
